#ifndef _CONSTANTS_H
#define _CONSTANTS_H

enum AxisType
{
	X_AXIS = 0,
	Y_AXIS,
	Z_AXIS
};


#define APPLICATION_WINDOW_HEIGHT 800
#define APPLICATION_WINDOW_WIDTH 800


#define CANVAS_LEFT 10
#define CANVAS_RIGHT 400
#define CANVAS_BOTTOM 10
#define CANVAS_TOP 400

#define COLOR_PANEL_LEFT 405
#define COLOR_PANEL_RIGHT 495
#define COLOR_PANEL_TOP 400
#define COLOR_PANEL_BOTTOM 10


#define MENUBAR_LEFT 10
#define MENUBAR_RIGHT 490
#define MENUBAR_TOP 499
#define MENUBAR_BOTTOM 480

#define TOOLBAR_LEFT 10
#define TOOLBAR_RIGHT 490
#define TOOLBAR_TOP 480
#define TOOLBAR_BOTTOM 410

#define GAP 4
#define COLOR_SQUARE_SIDE 30

#endif